//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.0
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProduceManager.PrdManager {
    using System.Runtime.Serialization;
    using System;
    using System.Data;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PrdManager.ShareWSSoap")]
    public interface ShareWSSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpdateFileVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetUpdateFileVersion(string strUrl, string FileName);
        
        // CODEGEN: 参数“GetUpdateFileByteResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUpdateFileByte", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        global::ProduceManager.PrdManager.GetUpdateFileByteResponse GetUpdateFileByte(global::ProduceManager.PrdManager.GetUpdateFileByteRequest request);
        
        // CODEGEN: 参数“FileReadResult”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileRead", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        global::ProduceManager.PrdManager.FileReadResponse FileRead(global::ProduceManager.PrdManager.FileReadRequest request);
        
        // CODEGEN: 参数“retBytes”需要其他方案信息，使用参数模式无法捕获这些信息。特定特性为“System.Xml.Serialization.XmlElementAttribute”。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FileSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        global::ProduceManager.PrdManager.FileSaveResponse FileSave(global::ProduceManager.PrdManager.FileSaveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ExecStoredProc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        object ExecStoredProc(string strConnectionString, string strSqlSPName, string strParaKeys, string[] strParaVals, string strRetType);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTableByStoredProc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetTableByStoredProc(string strConnectionString, string strSqlSPName, string strParaKeys, string[] strParaVals);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDataSetByStoredProc", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet GetDataSetByStoredProc(string strConnectionString, string strSqlSPName, string strParaKeys, string[] strParaVals);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUpdateFileByte", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUpdateFileByteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUrl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string FileName;
        
        public GetUpdateFileByteRequest() {
        }
        
        public GetUpdateFileByteRequest(string strUrl, string FileName) {
            this.strUrl = strUrl;
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetUpdateFileByteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetUpdateFileByteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] GetUpdateFileByteResult;
        
        public GetUpdateFileByteResponse() {
        }
        
        public GetUpdateFileByteResponse(byte[] GetUpdateFileByteResult) {
            this.GetUpdateFileByteResult = GetUpdateFileByteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileRead", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileReadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string strUrl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string FileName;
        
        public FileReadRequest() {
        }
        
        public FileReadRequest(string strUrl, string FileName) {
            this.strUrl = strUrl;
            this.FileName = FileName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileReadResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] FileReadResult;
        
        public FileReadResponse() {
        }
        
        public FileReadResponse(byte[] FileReadResult) {
            this.FileReadResult = FileReadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileSave", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileSaveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary")]
        public byte[] retBytes;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string FileName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string ImgUrl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string BigImgUrl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string SmallImgUrl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string RecentSmallImgUrl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public string RecentBigImgUrl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public string RecentOrgImgUrl;
        
        public FileSaveRequest() {
        }
        
        public FileSaveRequest(byte[] retBytes, string FileName, string ImgUrl, string BigImgUrl, string SmallImgUrl, string RecentSmallImgUrl, string RecentBigImgUrl, string RecentOrgImgUrl) {
            this.retBytes = retBytes;
            this.FileName = FileName;
            this.ImgUrl = ImgUrl;
            this.BigImgUrl = BigImgUrl;
            this.SmallImgUrl = SmallImgUrl;
            this.RecentSmallImgUrl = RecentSmallImgUrl;
            this.RecentBigImgUrl = RecentBigImgUrl;
            this.RecentOrgImgUrl = RecentOrgImgUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileSaveResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileSaveResponse {
        
        public FileSaveResponse() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShareWSSoapChannel : global::ProduceManager.PrdManager.ShareWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShareWSSoapClient : System.ServiceModel.ClientBase<global::ProduceManager.PrdManager.ShareWSSoap>, global::ProduceManager.PrdManager.ShareWSSoap {
        
        public ShareWSSoapClient() {
        }
        
        public ShareWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShareWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShareWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShareWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetUpdateFileVersion(string strUrl, string FileName) {
            return base.Channel.GetUpdateFileVersion(strUrl, FileName);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::ProduceManager.PrdManager.GetUpdateFileByteResponse global::ProduceManager.PrdManager.ShareWSSoap.GetUpdateFileByte(global::ProduceManager.PrdManager.GetUpdateFileByteRequest request) {
            return base.Channel.GetUpdateFileByte(request);
        }
        
        public byte[] GetUpdateFileByte(string strUrl, string FileName) {
            global::ProduceManager.PrdManager.GetUpdateFileByteRequest inValue = new global::ProduceManager.PrdManager.GetUpdateFileByteRequest();
            inValue.strUrl = strUrl;
            inValue.FileName = FileName;
            global::ProduceManager.PrdManager.GetUpdateFileByteResponse retVal = ((global::ProduceManager.PrdManager.ShareWSSoap)(this)).GetUpdateFileByte(inValue);
            return retVal.GetUpdateFileByteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::ProduceManager.PrdManager.FileReadResponse global::ProduceManager.PrdManager.ShareWSSoap.FileRead(global::ProduceManager.PrdManager.FileReadRequest request) {
            return base.Channel.FileRead(request);
        }
        
        public byte[] FileRead(string strUrl, string FileName) {
            global::ProduceManager.PrdManager.FileReadRequest inValue = new global::ProduceManager.PrdManager.FileReadRequest();
            inValue.strUrl = strUrl;
            inValue.FileName = FileName;
            global::ProduceManager.PrdManager.FileReadResponse retVal = ((global::ProduceManager.PrdManager.ShareWSSoap)(this)).FileRead(inValue);
            return retVal.FileReadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        global::ProduceManager.PrdManager.FileSaveResponse global::ProduceManager.PrdManager.ShareWSSoap.FileSave(global::ProduceManager.PrdManager.FileSaveRequest request) {
            return base.Channel.FileSave(request);
        }
        
        public void FileSave(byte[] retBytes, string FileName, string ImgUrl, string BigImgUrl, string SmallImgUrl, string RecentSmallImgUrl, string RecentBigImgUrl, string RecentOrgImgUrl) {
            global::ProduceManager.PrdManager.FileSaveRequest inValue = new global::ProduceManager.PrdManager.FileSaveRequest();
            inValue.retBytes = retBytes;
            inValue.FileName = FileName;
            inValue.ImgUrl = ImgUrl;
            inValue.BigImgUrl = BigImgUrl;
            inValue.SmallImgUrl = SmallImgUrl;
            inValue.RecentSmallImgUrl = RecentSmallImgUrl;
            inValue.RecentBigImgUrl = RecentBigImgUrl;
            inValue.RecentOrgImgUrl = RecentOrgImgUrl;
            global::ProduceManager.PrdManager.FileSaveResponse retVal = ((global::ProduceManager.PrdManager.ShareWSSoap)(this)).FileSave(inValue);
        }
        
        public object ExecStoredProc(string strConnectionString, string strSqlSPName, string strParaKeys, string[] strParaVals, string strRetType) {
            return base.Channel.ExecStoredProc(strConnectionString, strSqlSPName, strParaKeys, strParaVals, strRetType);
        }
        
        public System.Data.DataTable GetTableByStoredProc(string strConnectionString, string strSqlSPName, string strParaKeys, string[] strParaVals) {
            return base.Channel.GetTableByStoredProc(strConnectionString, strSqlSPName, strParaKeys, strParaVals);
        }
        
        public System.Data.DataSet GetDataSetByStoredProc(string strConnectionString, string strSqlSPName, string strParaKeys, string[] strParaVals) {
            return base.Channel.GetDataSetByStoredProc(strConnectionString, strSqlSPName, strParaKeys, strParaVals);
        }
    }
}
